spring:
  application:
    name: lab
  datasource: #data properties
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3312/account_system?useSSL=false&createDatabaseIfNotExist=true"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org: WARN
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor: TRACE


